# Generated by Django 4.2.11 on 2024-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_locations_company_logo_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
